apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-cluster
  namespace: postgresql-v1
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:15
  storage:
    size: 5Gi
    storageClass: standard
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1Gi"
  bootstrap:
    initdb:
      database: appdb
      owner: appuser
      secret:
        name: pg-secret
  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "256MB"